### ISSUE TITLE
FizzBuzz#Outputメソッドについて

### ISSUE THREAD

**Issue by mamepika** [ykikuchi1910/JavaPBL_Maven1#1]
Javaはメソッドの先頭文字は小文字にするルールがあります。
また、staticメソッドになっていますので、testコードでのインスタンス作成は不要です。
インスタンスメソッドにするなら、テストコードの修正が必要です。

**Comment by ykikuchi1910** [comment]
ありがとうございます。 @before でインスタンス作成するように直しました。

2020年4月12日(日) 20:54 mame_pika <notifications@github.com>:

**Comment by mamepika** [comment]
違います。
staticメソッドであればインスタンスの作成は不要です

**Comment by mamepika** [comment]
また、メソッド名が修正されていません

**Comment by ykikuchi1910** [comment]
ありがとうございます。メソッド名の小文字、インスタンス作成の削除、hello world もテストスクリプトを追加しました。

2020年4月14日(火) 15:43 mame_pika <notifications@github.com>:
